version: "3.10"

services:
  redis:
    image: redis
    restart: always

  webapp:
    restart: always
    build:
      context: ./app
    ports:
      - "8000:8000"
    command: ["python3", "./src/manage.py", "runserver", "0.0.0.0:8000"]

  worker:
    restart: always
    build:
      context: ./app
    command: ['celery', '--workdir=./src', '-A', 'BetBot', 'worker']
