# Generated by Django 4.1.1 on 2022-09-14 19:20

from django.db import migrations, models
import django.utils.timezone

import Data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
                ('name', models.CharField(default=Data.models.Bookmaker.__str__, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('bookmaker', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Data.bookmaker')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Data.category')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.category')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='Data.team')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_url', models.URLField()),
                ('bookmaker_url', models.URLField()),
                ('start_date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Sponsor search'), (2, 'Waiting for the start'), (3, 'Started'), (4, 'Ended'), (5, 'Waiting'), (6, 'Canceled')], default=0)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.bookmaker')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Data.event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.infosponsor')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeamBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.bookmaker')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.eventteam')),
            ],
        ),
        migrations.AddField(
            model_name='eventteam',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Data.game'),
        ),
        migrations.AddField(
            model_name='eventteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.team'),
        ),
    ]
